### ISSUE TITLE
Chat Template is not getting applied properly

### ISSUE THREAD

**Issue by prince14322** [FSoft-AI4Code/XMainframe#1]
Sample code [(link)](https://github.com/FSoft-AI4Code/XMainframe/tree/main?tab=readme-ov-file#inference) gives garbage output.

Here is that I got as output.
```
The given sentence is not factually correct.

The sentence states that "The United States has the most people in the world." However, this is not true. According to the World Bank, as of 2020, China has the most people in the world, with over 1.4 billion people. The United States ranks second with around 331 million people.

To provide a more accurate sentence, we can say: "The United States has the second-largest population in the world, after China."
```

After doing RCA, it was found that chat template was not getting properly applied to the input.
Can the team please have a look?

**Comment by vananh0905** [comment]
Hi @prince14322,

I just updated the inference script and the tokenizer. You can re-download and try out our model now.
Thank you for your attention.
