### ISSUE TITLE
tokenizer problem.

### ISSUE THREAD

**Issue by Trungght453** [FSoft-AI4Code/XMainframe#2]
Hi @vananh0905 

I reviewed your tokenizer file and noticed a few issues.

First, the IDs for special tokens are not clearly defined. For example, the EOS token is assigned multiple IDs, such as 0, 1, 2, and 100001.

Second, the chat template seems incorrect. I tested it with deepseek-ai/deepseek-llm-7b-chat, where the EOS token is defined as 100015 (which aligns with your model's training), and it generated good responses.

In my opinion, it would be beneficial to correct the tokenizer, particularly the special tokens and chat template.

**Comment by vananh0905** [comment]
Hi @Trungght453 

Thank you for your suggestion and we appreciate it.
Our code base is adapted from [alignment-handbook ](https://github.com/huggingface/alignment-handbook), so the chat template differs from others. I fixed the chat template for inference.

**Comment by Trungght453** [comment]
Hi @vananh0905 

You can try out this code to have a full view of your tokenizer problem:

```python
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("Fsoft-AIC/XMAiNframe-instruct-7b")
messages=[
    {'role':'system', 'content': "You are a helpful assistant"},
    {'role': 'user', 'content': 'What is the future of Mainframe?'}
]
inputs = tokenizer.apply_chat_template(messages, add_generation_prompt=True, return_tensors="pt")
tokenizer.decode(inputs[0])
```

![image](https://github.com/user-attachments/assets/1af67a7e-d1a7-4c21-8f99-a8c37793d33a)


After decoding, it only shows the system prompt and loses the user prompt.

**Comment by vananh0905** [comment]
I just updated the scripts for inference and tokenizer. You can re-download and try out our model now.
